name: Frontend CI/CD

on:
  push:
    branches:
      - develop
      - qa
      - main

  pull_request:
    branches:
      - develop
      - qa
      - main

jobs:

  # # =========================
  # # CI
  # # =========================
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v7

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v7
  #       with:
  #         node-version: 24
  #         cache: npm

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run ESLint
  #       run: npm run lint

  #     - name: Run tests
  #       run: npm run test

  #     - name: Build project
  #       run: npm run build

  # # =========================
  # # DEPLOY DEV
  # # =========================
  # deploy-dev:
  #   needs: build

  #   if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

  #   runs-on: ubuntu-latest

  #   environment: development

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v7

  #     - name: Install Vercel CLI
  #       run: npm install --global vercel

  #     - name: Deploy DEV
  #       run: vercel --token=${{ secrets.VERCEL_TOKEN }}

  # # =========================
  # # DEPLOY QA
  # # =========================
  # deploy-qa:
  #   needs: build

  #   if: github.event_name == 'push' && github.ref == 'refs/heads/qa'

  #   runs-on: ubuntu-latest

  #   environment: qa

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v7

  #     - name: Install Vercel CLI
  #       run: npm install --global vercel

  #     - name: Deploy QA
  #       run: vercel --token=${{ secrets.VERCEL_TOKEN }}

  # # =========================
  # # DEPLOY PRODUCCIÓN
  # # =========================
  # deploy-production:
  #   needs: build

  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'

  #   runs-on: ubuntu-latest

  #   environment: production

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v7

  #     - name: Install Vercel CLI
  #       run: npm install --global vercel

  #     - name: Deploy Production
  #       run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
